services:
  db:
    image: postgres:latest
    container_name: auth-db
    env_file:
      - ./docker/db.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: